/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.LoginAdmin;

import BUS.NhanVienBus;
import GUI.Admin.Admin;
import GUI.Login.*;
import GUI.NVBanHang.NhanVienBanHang;
import ProcessingFunction.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import javax.swing.*;

/**
 *
 * @author MTHUAN
 */
public class Login extends javax.swing.JFrame {

    NhanVienBus nhanvienbus = new NhanVienBus();
    private boolean isBeginUser = true;
    private boolean isBeginPass = true;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        initialization();
        performEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        exitBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Tên đăng nhập");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 270, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user_48px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/key_2_100px.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 40, 40));

        loginBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginBtn.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(153, 102, 255));
        loginBtn.setText("Đăng nhập");
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/book_60px.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đăng nhập(Admin)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 90, 400, -1));

        password.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Mật khẩu");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 270, -1));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(51, 51, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/export_64px.png"))); // NOI18N
        exitBtn.setText("Thoát");
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        background.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1092593.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0));
        //Username
        username.setBackground(new Color(0, 0, 0, 0));
        username.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));
        //Password
        password.setBackground(new Color(0, 0, 0, 0));
        password.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));
    }

    private void performEvent() {
        exitBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình ?", "Thoátchương trình", 0) == 0) {
                    System.exit(0);
                }
            }
        });

        loginBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (checkInput() == false) {
                    return;
                }
                String result = nhanvienbus.checkLogin(username.getText(), String.valueOf(password.getPassword()));
                JOptionPane.showMessageDialog(null, result);

                if (result.compareTo("Đăng nhập thành công") == 0) {
                    int right = nhanvienbus.getRightOfStaff(username.getText());
                    if (right == 1) {
                        new Admin(nhanvienbus.getStaffByUserName(username.getText())).setVisible(true);
                        dispose();
                    } else if (right == 2) {
                        new NhanVienBanHang(nhanvienbus.getStaffByUserName(username.getText())).setVisible(true);
                        dispose();
                    }
                }
            }
        });

        username.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (isBeginUser == false) {
                    return;
                }
                username.setText("");
                password.setText("");
                isBeginUser = false;
                isBeginPass = false;
            }
        });

        password.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (isBeginPass == false) {
                    return;
                }
                username.setText("");
                password.setText("");
                isBeginUser = false;
                isBeginPass = false;
            }
        });

        password.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (checkInput() == false) {
                        return;
                    }
                    String result = nhanvienbus.checkLogin(username.getText(), String.valueOf(password.getPassword()));
                    JOptionPane.showMessageDialog(null, result);

                    if (result.compareTo("Đăng nhập thành công") == 0) {
                        int right = nhanvienbus.getRightOfStaff(username.getText());
                        if (right == 1) {
                            new Admin(nhanvienbus.getStaffByUserName(username.getText())).setVisible(true);
                            dispose();
                        } else if (right == 2) {
                            new NhanVienBanHang(nhanvienbus.getStaffByUserName(username.getText())).setVisible(true);
                            dispose();
                        }
                    }
                }
            }
        });
    }

    public boolean checkInput() {
        //Chưa nhập tên đăng nhập
        if (username.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên đăng nhập");
            return false;
        }
        //Chưa nhập mật khẩu
        if (String.valueOf(password.getPassword()).compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mật khẩu");
            return false;
        }
        return true;
    }
}
