/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QLNhanVien;

import BUS.NhanVienBus;
import DTO.HoaDon;
import DTO.NhanVien;
import ProcessingFunction.ReadExcel;
import ProcessingFunction.WriteExcel;
import Test.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINHTHUAN
 */
public class QuanLyNhanVien extends javax.swing.JPanel{
    NhanVienBus nvbus = new NhanVienBus();
    ///SuaNhanVien suanv = new SuaNhanVien(nv);
    NhanVien nv = null;
    /**
     * Creates new form DefaultPanel
     */
    public QuanLyNhanVien() {
        initComponents();
        initialization();
        performEvent();
    }
    
    public QuanLyNhanVien(NhanVien nhanvien) {
        setNv(nhanvien);
        initComponents();
        initialization();
        performEvent();
    }

    public NhanVien getNv() {
        return nv;
    }

    public void setNv(NhanVien nv) {
        this.nv = nv;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        exportPdfBtn2 = new javax.swing.JButton();
        editBtn1 = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        statisticalBtn = new javax.swing.JButton();
        importExcelBtn = new javax.swing.JButton();
        exportExcelBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1120, 660));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1050, 450));

        exportPdfBtn2.setBackground(new java.awt.Color(255, 255, 255));
        exportPdfBtn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exportPdfBtn2.setForeground(new java.awt.Color(153, 51, 255));
        exportPdfBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search_50px.png"))); // NOI18N
        exportPdfBtn2.setText("Tìm Kiếm");
        exportPdfBtn2.setBorder(null);
        add(exportPdfBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 180, -1));

        editBtn1.setBackground(new java.awt.Color(255, 255, 255));
        editBtn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        editBtn1.setForeground(new java.awt.Color(153, 51, 255));
        editBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_64px.png"))); // NOI18N
        editBtn1.setText("Cập nhật");
        editBtn1.setBorder(null);
        add(editBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 180, -1));

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        editBtn.setForeground(new java.awt.Color(153, 51, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_48px.png"))); // NOI18N
        editBtn.setText("Sửa");
        editBtn.setBorder(null);
        add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 180, -1));

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addBtn.setForeground(new java.awt.Color(153, 51, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        addBtn.setText("Thêm");
        addBtn.setBorder(null);
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, -1));

        statisticalBtn.setBackground(new java.awt.Color(255, 255, 255));
        statisticalBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        statisticalBtn.setForeground(new java.awt.Color(153, 51, 255));
        statisticalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/area_chart_48px.png"))); // NOI18N
        statisticalBtn.setText("Thống kê");
        statisticalBtn.setBorder(null);
        add(statisticalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 180, -1));

        importExcelBtn.setBackground(new java.awt.Color(255, 255, 255));
        importExcelBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        importExcelBtn.setForeground(new java.awt.Color(153, 51, 255));
        importExcelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/import_file_48px.png"))); // NOI18N
        importExcelBtn.setText("Nhập Excel");
        importExcelBtn.setBorder(null);
        add(importExcelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 180, -1));

        exportExcelBtn.setBackground(new java.awt.Color(255, 255, 255));
        exportExcelBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exportExcelBtn.setForeground(new java.awt.Color(153, 51, 255));
        exportExcelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/export_csv_60px.png"))); // NOI18N
        exportExcelBtn.setText("Xuất Excel");
        exportExcelBtn.setBorder(null);
        add(exportExcelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, 180, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editBtn1;
    private javax.swing.JButton exportExcelBtn;
    private javax.swing.JButton exportPdfBtn2;
    private javax.swing.JButton importExcelBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton statisticalBtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        //Define size for JPanel
        this.setSize(1120, 660);
        initTable();
        loadTableData();
    }

    private void performEvent() {
        
        ActionListener ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                switch(e.getActionCommand()){
                    case "Thêm":{
                        new ThemNhanVien().setVisible(true);
                        break;
                    }
                    
                    case "Tìm Kiếm":{
                        new TimKiem().setVisible(true);
                        break;
                    }
                    case "Cập nhật":{
                        loadTableData();
                        JOptionPane.showMessageDialog(null, "Đã reload");
                        break;
                    }
                    case "Thống kê":{
                        new ThongKe().setVisible(true);
                        break;
                    }
                    case "Xuất Excel":{
                        WriteExcel write = new WriteExcel();
                        write.writeStaff();
                        break;
                    }
                    case "Nhập Excel":{
                        ReadExcel read = new ReadExcel();
                        read.readExcelStaff();
                        break;
                    }
                    case "Sửa":{
                        /*suanv = new SuaNhanVien(nv);
                        suanv.setVisible(true);*/
                        new SuaNhanVien(nv).setVisible(true);
                        break;
                    }
                }
            }
        };
        
        Arrays.stream(this.getComponents()).forEach(c ->{
            if(c instanceof JButton){
                ((JButton)c).addActionListener(ac);
                ((JButton)c).setActionCommand(((JButton)c).getActionCommand());
            }
        });
        
        /*suanv.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                loadTableData();
                suanv.setVisible(false);
            }
        
        });*/
        
    }
    
    private void initTable() {
        String []header = {"Mã nhân viên","Tên nhân viên","Ngày Sinh","Giới tính (Nam ?)","SĐT","Địa chỉ","Mã quyền","Tên đăng nhập","Mật khẩu","Trạng Thái"};
        DefaultTableModel defaults = (DefaultTableModel) table.getModel();
        
        Arrays.stream(header).forEach(s -> {
            defaults.addColumn(s);
        });

        table.setRowHeight(25);
    }

    private void loadTableData() {
        removeAllTableData();
        DefaultTableModel defaults = (DefaultTableModel) table.getModel();
        
        ArrayList<NhanVien> data = nvbus.getAllData();
        Object []obj = new Object[10];
        
        for(NhanVien nv : data){
            obj[0] = nv.getMaNhanVien();
            obj[1] = nv.getTenNhanVien();
            obj[2] = nv.getNgaySinh().toString();
            obj[3] = nv.isGioiTinh();
            obj[4] = nv.getSDT();
            obj[5] = nv.getDiaChi();
            obj[6] = nv.getMaQuyen();
            obj[7] = nv.getTenDangNhap();
            obj[8] = nv.getMatKhau();
            obj[9] = nv.isTrangThai();
            defaults.addRow(obj);
            
        }
    }
    
    private void removeAllTableData() {
        DefaultTableModel defaults = (DefaultTableModel) table.getModel();
        for (int i = defaults.getRowCount() - 1; i >= 0; i--) {
            defaults.removeRow(i);
        }
    }
}
