/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QLTaiKhoanKH;

import BUS.TaiKhoanBus;
import DTO.TaiKhoan;
import GUI.QLTaiKhoanKH.KhoaTaiKhoan.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author MINHTHUAN
 */
public class KhoaTaiKhoan extends javax.swing.JFrame {
    TaiKhoanBus tkbus = new TaiKhoanBus();
    /**
     * Creates new form KhoaTaiKhoan
     */
    public KhoaTaiKhoan() {
        initComponents();  
        initialization();
        event();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        statususername = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnuser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Tài khoản");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        username.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 270, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Trạng thái");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        statususername.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(statususername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 270, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mở/Khóa Tài Khoản");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 90));

        btnuser.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnuser.setText("Thay đổi");
        jPanel1.add(btnuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoaTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoaTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoaTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoaTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoaTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> statususername;
    private javax.swing.JComboBox<String> username;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        loadCombobox();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }
    private void loadCombobox() {
        ArrayList <TaiKhoan> tk = tkbus.getAllData();
        username.addItem("[Lựa Chọn]");
        for(TaiKhoan arr: tk)
        {
            username.addItem(String.valueOf(arr.getTenDangNhap()));
        }
        
        statususername.addItem("Đang Hoạt Động");
        statususername.addItem("Không Hoạt Động");
    }
    
    private void event() {
        username.addActionListener(new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(username.getSelectedIndex()==0)
                {
                    statususername.setSelectedIndex(0);
                    return;
                }
                String id = String.valueOf(username.getSelectedItem());
                TaiKhoan tk = tkbus.getTKById(id);
                boolean st = tk.isTrangThai();
                statususername.setSelectedIndex((st==true)?0:1);
           }
        });
        btnuser.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(username.getSelectedIndex()==0)
                {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn Tài Khoản !!");
                    return;
                }
                String id = String.valueOf( username.getSelectedItem());
                
                boolean st = statususername.getSelectedIndex() == 0 ? true : false;
                boolean ok = tkbus.Update(String.valueOf(id), st);
                System.out.println(st);
                     if(ok)
                     {
                         JOptionPane.showMessageDialog(null, "Sửa Thành Công");
                         return;
                     }
                     JOptionPane.showMessageDialog(null, "Không thể sửa !!");
            }
        });
    }
}
