/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KhachHang;

import BUS.ChiTietHoaDonBus;
import BUS.HoaDonBus;
import BUS.NhanVienBus;
import DTO.ChiTietHoaDon;
import DTO.HoaDon;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author MINHTHUAN
 */
public class contentHistory extends javax.swing.JPanel {
    HoaDon hoadon = null;
    NhanVienBus nvbus = new NhanVienBus();
    ChiTietHoaDonBus cthdbus = new ChiTietHoaDonBus();
    HoaDonBus hdbus = new HoaDonBus();
    /**
     * Creates new form contentHistory
     */
    public contentHistory() {
        initComponents();
    }
    
    public contentHistory(HoaDon hd) {
        initComponents();
        setHoadon(hd);
        initialization();
        performEvent();
    }

    public HoaDon getHoadon() {
        return hoadon;
    }

    public void setHoadon(HoaDon hoadon) {
        this.hoadon = hoadon;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idBill = new javax.swing.JTextField();
        timeBill = new javax.swing.JTextField();
        dateBill = new javax.swing.JTextField();
        viewDetail = new javax.swing.JButton();
        staff = new javax.swing.JTextField();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 2));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/bill_60px.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 51, -1, -1));

        idBill.setEditable(false);
        idBill.setBackground(new java.awt.Color(255, 255, 255));
        idBill.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        background.add(idBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 158, 240, -1));

        timeBill.setEditable(false);
        timeBill.setBackground(new java.awt.Color(255, 255, 255));
        timeBill.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        background.add(timeBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 252, 240, -1));

        dateBill.setEditable(false);
        dateBill.setBackground(new java.awt.Color(255, 255, 255));
        dateBill.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        background.add(dateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 205, 240, -1));

        viewDetail.setBackground(new java.awt.Color(255, 255, 255));
        viewDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewDetail.setForeground(new java.awt.Color(0, 51, 255));
        viewDetail.setText("Xem Chi Tiết");
        background.add(viewDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        staff.setEditable(false);
        staff.setBackground(new java.awt.Color(255, 255, 255));
        staff.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        background.add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 293, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField dateBill;
    private javax.swing.JTextField idBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField staff;
    private javax.swing.JTextField timeBill;
    private javax.swing.JButton viewDetail;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        idBill.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0,new Color(65,247,247)));
        dateBill.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0,new Color(65,247,247)));
        timeBill.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(65,247,247)));
        staff.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(65,247,247)));
        loadData();
        setSize(270, 400);
    }

    private void loadData() {
        idBill.setText("Mã Hóa Đơn : " + hoadon.getMaHoaDon());
        dateBill.setText("Ngày Lập : " + hoadon.getNgayLap().toString());
        timeBill.setText("Giờ Lập : " + hoadon.getGioLap().toString());
        if(hoadon == null || hoadon.getTrangThai() == 0){
            staff.setText("Nhân Viên Xác Nhận : Chưa được xác nhận");
            return;
        }
        staff.setText("Nhân Viên Xác Nhận : " + nvbus.getNameById(hoadon.getMaNhanVien()));
    }

    private void performEvent() {
        viewDetail.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String value = idBill.getText().substring(13);
                int id = 0;
                try {
                    id = Integer.valueOf(value);
                } catch (Exception ex) {
                    return;
                }
                ArrayList<ChiTietHoaDon> data = cthdbus.getDataById(id);
                HoaDon hd = hdbus.getBillById(id);
                new XemChiTiet(hd, data).setVisible(true);
                
            }
        });
    }
}
