/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KhachHang;

import BUS.ChiTietHoaDonBus;
import BUS.KhachHangBus;
import DTO.ChiTietHoaDon;
import DTO.KhachHang;
import GUI.Login.Login;
import GUI.Login.Register_1;
import GUI.Login.changePassword;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MINHTHUAN
 */
public class Home extends javax.swing.JFrame {
    KhachHang kh = null;
    CartShopping cart = new CartShopping();
    Product product = new Product();
    LichSu lichsu = new LichSu();
    ChiTietHoaDonBus cthdbus = new ChiTietHoaDonBus();
    TrangChu trangchu = new TrangChu();
    SuaKhachHang suakh = new SuaKhachHang(kh);
    KhachHangBus khbus = new KhachHangBus();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        initialization();
        performEvent();
        performSetting();
    }
    
    public Home(KhachHang kh,ArrayList<ChiTietHoaDon> data) {
        setKh(kh);
        cart.setDataCart(data);
        initComponents();
        initialization();
        performEvent();
        performSetting();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        setting = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        changePassBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Hello = new javax.swing.JLabel();
        settingLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setting.setBackground(new java.awt.Color(204, 255, 255));
        setting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(24, 122, 220));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/login_rounded_64px.png"))); // NOI18N
        loginBtn.setText("Đăng nhập");
        loginBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setting.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 50));

        registerBtn.setBackground(new java.awt.Color(255, 255, 255));
        registerBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(24, 122, 220));
        registerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/register.png"))); // NOI18N
        registerBtn.setText("Đăng ký");
        registerBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setting.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 50));

        changePassBtn.setBackground(new java.awt.Color(255, 255, 255));
        changePassBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        changePassBtn.setForeground(new java.awt.Color(24, 122, 220));
        changePassBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/change_password_64px.png"))); // NOI18N
        changePassBtn.setText("Đổi mật khẩu");
        changePassBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setting.add(changePassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 50));

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(24, 122, 220));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/sign_out_64px.png"))); // NOI18N
        logoutBtn.setText("Đăng xuất");
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setting.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 50));

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        editBtn.setForeground(new java.awt.Color(24, 122, 220));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/design_64px.png"))); // NOI18N
        editBtn.setText("Sửa thông tin");
        editBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setting.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        background.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 250, 250));

        jPanel3.setBackground(new java.awt.Color(33, 142, 251));

        Hello.setBackground(new java.awt.Color(33, 144, 255));
        Hello.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Hello.setForeground(new java.awt.Color(255, 255, 255));
        Hello.setText("Xin chào : ");

        settingLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        settingLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/triangle_arrow_24px.png"))); // NOI18N
        settingLabel.setText("Chức năng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hello, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                .addComponent(settingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Hello)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(settingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 70));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/home_64px.png"))); // NOI18N
        jButton1.setText("Trang Chủ");
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 60));

        jButton2.setBackground(new java.awt.Color(0, 255, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/books_64px.png"))); // NOI18N
        jButton2.setText("Sản Phẩm");
        background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 240, 60));

        jButton3.setBackground(new java.awt.Color(16, 168, 243));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/shopping_cart_64px.png"))); // NOI18N
        jButton3.setText("Giỏ Hàng");
        background.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 240, 60));

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User/history.png"))); // NOI18N
        jButton4.setText("Lịch Sử");
        background.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 240, 60));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1200, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hello;
    private javax.swing.JPanel background;
    private javax.swing.JButton changePassBtn;
    private javax.swing.JPanel content;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPanel setting;
    private javax.swing.JLabel settingLabel;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setting.setVisible(false);
        addJPanelIntoContent(trangchu);
        hideAllButton();
        if(kh == null){
            return;
        }
        Hello.setText("Xin chào : " + kh.getTenKhachHang());
        
    }

    private void performEvent() {
        ActionListener ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Chuyển tất cả dữ liệu từ Sản phẩm -> Giỏ hàng
                ArrayList<ChiTietHoaDon> data = cthdbus.appendDetailBill(product.getCartData(), cart.getDataCart());
                cart = new CartShopping(data,getKh());
                product.setCartData(new ArrayList<>());
                setting.setVisible(false);
                switch (e.getActionCommand()) {
                    case "Trang Chủ": {
                        hideAllButton();
                        addJPanelIntoContent(trangchu);
                        break;
                    }
                    case "Sản Phẩm": {
                        showAllButton();
                        addJPanelIntoContent(product);
                        break;
                    }
                    case "Giỏ Hàng": {
                        showAllButton();
                        addJPanelIntoContent(cart);
                        break;
                    }
                    case "Lịch Sử": {
                        showAllButton();
                        lichsu = new LichSu(kh);
                        addJPanelIntoContent(lichsu);
                        break;
                    }
                }
            }
        };
        Arrays.stream(background.getComponents()).forEach(
                c -> {
                    if (c instanceof JButton) {
                        ((JButton) c).addActionListener(ac);
                        ((JButton) c).setActionCommand(((JButton) c).getActionCommand());
                    }
                }
        );
        
        Arrays.stream(content.getComponents()).forEach(c->{
            if(c instanceof TrangChu){
                Arrays.stream(((JPanel)c).getComponents()).forEach(c1->{
                    Arrays.stream(((JPanel)c1).getComponents()).forEach(c2->{
                        if(c2 instanceof JButton){
                            ((JButton)c2).addActionListener(ac);
                            ((JButton)c2).setActionCommand(((JButton)c2).getActionCommand());
                        }
                    });
                });
            }
        });

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                ArrayList<ChiTietHoaDon> data = cthdbus.appendDetailBill(product.getCartData(), cart.getDataCart());
                cart = new CartShopping(data,kh);
                product.setCartData(new ArrayList<>());
                cart.recoveryNumberBook();
                System.exit(0);
            }
        });
        suakh.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                kh = khbus.getKHById(kh.getMaKhachHang());
                new Home(kh, null).setVisible(true);
                dispose();
            }
        });
        
    }

    private void addJPanelIntoContent(JPanel p) {
        content.removeAll();
        content.revalidate();
        content.repaint();
        p.setSize(1200, 640);
        p.setVisible(true);
        content.add(p);
    }

    public KhachHang getKh() {
        return kh;
    }

    public void setKh(KhachHang kh) {
        this.kh = kh;
    }

    private void performSetting() {
        settingLabel.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e){
                if(setting.isVisible()){
                    setting.setVisible(false);
                }
                else{
                    setting.setVisible(true);
                }
            }        
        });
        
        ActionListener ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setting.setVisible(false);
                switch(e.getActionCommand()){
                    case "Đăng nhập":{
                        if(kh != null){
                            JOptionPane.showMessageDialog(null, "Bạn đã đăng nhập");
                            return;
                        }
                        new Login(cart.getDataCart()).setVisible(true);
                        dispose();
                        break;
                    }
                    case "Đăng ký":{
                        if(kh != null){
                            JOptionPane.showConfirmDialog(null, "Bạn cần đăng xuất trước khi đăng ký");
                            return;
                        }
                        new Register_1(cart.getDataCart()).setVisible(true);
                        dispose();
                        break;
                    }
                    case "Đổi mật khẩu":{
                        if(kh == null){
                            JOptionPane.showMessageDialog(null, "Bạn chưa đăng nhập");
                            return;
                        }
                        new changePassword(kh,cart.getDataCart()).setVisible(true);
                        dispose();
                        break;
                    }
                    case "Đăng xuất":{
                        if(kh == null){
                            JOptionPane.showMessageDialog(null, "Bạn chưa đăng nhập");
                            return;
                        }
                        new Home(null,cart.getDataCart()).setVisible(true);
                        dispose();
                        
                        break;
                    }
                    case "Sửa thông tin":{
                        if(kh == null){
                            JOptionPane.showMessageDialog(null, "Bạn chưa đăng nhập");
                            return;
                        }
                        suakh = new SuaKhachHang(kh);
                        suakh.setVisible(true);
                        break;
                    }
                }
            }
        };
        for(Component c : setting.getComponents()){
            if(c instanceof JButton){
                ((JButton)c).addActionListener(ac);
                ((JButton)c).setActionCommand(((JButton)c).getActionCommand());
            }
        }
    }
    
    public void hideAllButton(){
        for(Component c : background.getComponents()){
            if(c instanceof JButton){
                ((JButton)c).setVisible(false);
            }
        }
    }
    public void showAllButton(){
        for(Component c : background.getComponents()){
            if(c instanceof JButton){
                ((JButton)c).setVisible(true);
            }
        }
    }
}
