/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KhachHang;

import BUS.ChiTietHoaDonBus;
import BUS.HoaDonBus;
import DTO.ChiTietHoaDon;
import DTO.HoaDon;
import DTO.KhachHang;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author MINHTHUAN
 */
public class LichSu extends javax.swing.JPanel {
    KhachHang khachhang = null;
    HoaDonBus hdbus = new HoaDonBus();
    ChiTietHoaDonBus cthdbus = new ChiTietHoaDonBus();
    /**
     * Creates new form LichSu
     */
    public LichSu() {
        initComponents();
        initialization();
    }
    
    public LichSu(KhachHang kh) {
        setKhachhang(kh);
        initComponents();
        initialization();
    }

    public KhachHang getKhachhang() {
        return khachhang;
    }

    public void setKhachhang(KhachHang khachhang) {
        this.khachhang = khachhang;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollContent = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(scrollContent, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollContent, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollContent;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        loadData();
    }

    private void loadData() {
        if(khachhang == null) return;
        ArrayList<HoaDon> data = hdbus.getAllData();
        
        Container container = new Container();
        int col = 4;
        int row = data.size() % 3 == 0 ? data.size() / 3 : data.size() / 3 + 1;
        
        for(HoaDon hd : data){
            JPanel p = new contentHistory(hd);
            p.setVisible(true);
            container.add(p);
        }
        
        container.setLayout(new GridLayout(row, col));
        scrollContent.getViewport().setView(container);
    }
}
