/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QLPhieuNhap;

import BUS.PhieuNhapBus;
import DAO.PhieuNhapDao;
import DTO.NhanVien;
import DTO.PhieuNhap;
import DTO.Sach;
import GUI.QLSach.SuaSach;
import GUI.QLSach.ThongKe;
import GUI.QLSach.TimKiem;
import ProcessingFunction.ReadExcel;
import ProcessingFunction.WriteExcel;
import ProcessingFunction.WritePdf;
import Test.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINHTHUAN
 */
public class QuanLyPhieuNhap extends javax.swing.JPanel {
    PhieuNhapBus pnbus = new PhieuNhapBus();
    NhanVien nv = null;
    /**
     * Creates new form DefaultPanel
     */
    public QuanLyPhieuNhap(NhanVien nv) {
        this.nv = nv;
        initComponents();
        initialization();
        performEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        headControlPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        exportPdfBtn2 = new javax.swing.JButton();
        editBtn1 = new javax.swing.JButton();
        bottomControlPanel = new javax.swing.JPanel();
        exportPdfBtn = new javax.swing.JButton();
        statisticalBtn = new javax.swing.JButton();
        importExcelBtn = new javax.swing.JButton();
        exportExcelBtn = new javax.swing.JButton();
        exportPdfBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1120, 660));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 1050, 380));

        headControlPanel.setBackground(new java.awt.Color(255, 255, 255));

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addBtn.setForeground(new java.awt.Color(153, 51, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        addBtn.setText("Thêm");
        addBtn.setBorder(null);

        exportPdfBtn2.setBackground(new java.awt.Color(255, 255, 255));
        exportPdfBtn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exportPdfBtn2.setForeground(new java.awt.Color(153, 51, 255));
        exportPdfBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search_50px.png"))); // NOI18N
        exportPdfBtn2.setText("Tìm Kiếm");
        exportPdfBtn2.setBorder(null);

        editBtn1.setBackground(new java.awt.Color(255, 255, 255));
        editBtn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        editBtn1.setForeground(new java.awt.Color(153, 51, 255));
        editBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_64px.png"))); // NOI18N
        editBtn1.setText("Cập nhật");
        editBtn1.setBorder(null);

        javax.swing.GroupLayout headControlPanelLayout = new javax.swing.GroupLayout(headControlPanel);
        headControlPanel.setLayout(headControlPanelLayout);
        headControlPanelLayout.setHorizontalGroup(
            headControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headControlPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(exportPdfBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        headControlPanelLayout.setVerticalGroup(
            headControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(exportPdfBtn2)
                    .addComponent(editBtn1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(headControlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1120, -1));

        bottomControlPanel.setBackground(new java.awt.Color(255, 255, 255));

        exportPdfBtn.setBackground(new java.awt.Color(255, 255, 255));
        exportPdfBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exportPdfBtn.setForeground(new java.awt.Color(153, 51, 255));
        exportPdfBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pdf_48px.png"))); // NOI18N
        exportPdfBtn.setText("Xuất PDF");
        exportPdfBtn.setBorder(null);

        statisticalBtn.setBackground(new java.awt.Color(255, 255, 255));
        statisticalBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        statisticalBtn.setForeground(new java.awt.Color(153, 51, 255));
        statisticalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/area_chart_48px.png"))); // NOI18N
        statisticalBtn.setText("Thống kê");
        statisticalBtn.setBorder(null);

        importExcelBtn.setBackground(new java.awt.Color(255, 255, 255));
        importExcelBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        importExcelBtn.setForeground(new java.awt.Color(153, 51, 255));
        importExcelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/import_file_48px.png"))); // NOI18N
        importExcelBtn.setText("Nhập Excel");
        importExcelBtn.setBorder(null);

        exportExcelBtn.setBackground(new java.awt.Color(255, 255, 255));
        exportExcelBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exportExcelBtn.setForeground(new java.awt.Color(153, 51, 255));
        exportExcelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/export_csv_60px.png"))); // NOI18N
        exportExcelBtn.setText("Xuất Excel");
        exportExcelBtn.setBorder(null);

        exportPdfBtn1.setBackground(new java.awt.Color(255, 255, 255));
        exportPdfBtn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exportPdfBtn1.setForeground(new java.awt.Color(153, 51, 255));
        exportPdfBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/more_details_50px.png"))); // NOI18N
        exportPdfBtn1.setText("Xem chi tiết");
        exportPdfBtn1.setBorder(null);

        javax.swing.GroupLayout bottomControlPanelLayout = new javax.swing.GroupLayout(bottomControlPanel);
        bottomControlPanel.setLayout(bottomControlPanelLayout);
        bottomControlPanelLayout.setHorizontalGroup(
            bottomControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomControlPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(exportPdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statisticalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportPdfBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(importExcelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportExcelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        bottomControlPanelLayout.setVerticalGroup(
            bottomControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportPdfBtn)
                    .addComponent(statisticalBtn)
                    .addComponent(importExcelBtn)
                    .addComponent(exportExcelBtn)
                    .addComponent(exportPdfBtn1))
                .addGap(5, 5, 5))
        );

        add(bottomControlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1120, 70));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Quản Lý Phiếu Nhập");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 340, 80));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel bottomControlPanel;
    private javax.swing.JButton editBtn1;
    private javax.swing.JButton exportExcelBtn;
    private javax.swing.JButton exportPdfBtn;
    private javax.swing.JButton exportPdfBtn1;
    private javax.swing.JButton exportPdfBtn2;
    private javax.swing.JPanel headControlPanel;
    private javax.swing.JButton importExcelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton statisticalBtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        //Define size for JPanel
        this.setSize(1120, 660);
        initTable();
        loadTableData();        
    }

    private void performEvent() {
        ActionListener ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                switch (e.getActionCommand()) {
                    case "Thêm": {
                        new ThemPhieuNhap(nv).setVisible(true);
                        break;
                    }
                    case "Tìm Kiếm": {
                        new GUI.QLPhieuNhap.TimKiem().setVisible(true);
                        break;
                    }
                    case "Thống kê": {
                        new ThongKePN().setVisible(true);
                        break;
                    }
                    case "Nhập Excel": {
                        ProcessingFunction.ReadExcel read = new ReadExcel();
                        read.ReadExcelReceipt();
                        break;
                    }
                    case "Xuất Excel": {
                        int select = table.getSelectedRow();
                        if(select < 0){
                            JOptionPane.showMessageDialog(null, "Vui lòng chọn Phiếu nhập để xuất Excel");
                            return;
                        }
                        pnbus.writeExcel(Integer.valueOf(String.valueOf(table.getValueAt(select, 0))));
                        break;
                    }
                    case "Xem chi tiết": {
                        int select = table.getSelectedRow();
                        if(select < 0){
                            JOptionPane.showMessageDialog(null, "Vui lòng chọn Phiếu nhập để xem chi tiết");
                            return;
                        }
                        PhieuNhap pn = pnbus.getDataById(Integer.valueOf(String.valueOf(table.getValueAt(select, 0))));
                        new XemChiTiet(pn).setVisible(true);
                        break;
                    }
                    case "Cập nhật":{
                        loadTableData();
                        break;
                    }
                    case "Xuất PDF":{
                        int select = table.getSelectedRow();
                        if(select < 0){
                            JOptionPane.showMessageDialog(null, "Vui lòng chọn Phiếu nhập để xuất Pdf");
                            return;
                        }
                        int id = Integer.valueOf(String.valueOf(table.getValueAt(select, 0)));
                        ProcessingFunction.WritePdf pdf = new WritePdf();
                        pdf.writeRecept(id);
                        break;
                    }
                }
            }
        };
        Arrays.stream(headControlPanel.getComponents()).forEach(c -> {
            if (c instanceof JButton) {
                ((JButton) c).addActionListener(ac);
                ((JButton) c).setActionCommand(((JButton) c).getActionCommand());
            }
        });
        Arrays.stream(bottomControlPanel.getComponents()).forEach(c -> {
            if (c instanceof JButton) {
                ((JButton) c).addActionListener(ac);
                ((JButton) c).setActionCommand(((JButton) c).getActionCommand());
            }
        });
    }
    
    public void removeAllTable() {
        DefaultTableModel defaults = (DefaultTableModel) table.getModel();
        for (int i = defaults.getRowCount() - 1; i >= 0; i--) {
            defaults.removeRow(i);
        }
    }

    private void initTable() {
        String []header = {"Mã phiếu nhập","Mã nhân viên","Mã nhà cung cấp","Ngày nhập","Giờ nhập"};
        DefaultTableModel defaults = (DefaultTableModel) table.getModel();

        Arrays.stream(header).forEach(s -> {
            defaults.addColumn(s);
        });

        table.setRowHeight(25);
    }

    private void loadTableData() {
        removeAllTable();
        ArrayList<PhieuNhap> data = pnbus.getAllData();
        DefaultTableModel defaults = (DefaultTableModel) table.getModel();
        for(PhieuNhap pn : data){
            Object []obj = new Object[5];
            obj[0] = pn.getMaPhieuNhap();
            obj[1] = pn.getMaNhanVien();
            obj[2] = pn.getMaNhaCungCap();
            obj[3] = pn.getNgayNhap();
            obj[4] = pn.getGioNhap();
            defaults.addRow(obj);
        }
    }
}
