/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.NVQuanKho;

import GUI.Admin.*;
import DTO.NhanVien;
import GUI.LoginAdmin.Login;
import GUI.QLHoaDon.QuanLyHoaDon;
import GUI.QLKhachHang.QuanLyKhachHang;
import GUI.QLKhuyenMai.QuanLyKhuyenMai;
import GUI.QLNhanVien.QuanLyNhanVien;
import GUI.QLPhieuNhap.QuanLyPhieuNhap;
import GUI.QLSach.QuanLySach;
import GUI.QLTaiKhoanKH.QuanLyTaiKhoan;
import GUI.QLTheLoai.QuanLyTheLoai;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MINHTHUAN
 */
public class NhanVienQuanKho extends javax.swing.JFrame {
    JPanel home = new Home();
    JPanel book = new QuanLySach();
    JPanel bill = new QuanLyHoaDon();
    JPanel receipt = null;
    JPanel accountCus = new QuanLyTaiKhoan();
    JPanel staff = new QuanLyNhanVien();
    JPanel supplier = new GUI.QLNhaCungCap.QuanLyNhaCungCap();
    JPanel customer = new QuanLyKhachHang();
    JPanel sale = new QuanLyKhuyenMai();
    JPanel theloai = new QuanLyTheLoai();
    
    /**
     * Creates new form Admin
     */
    public NhanVienQuanKho() {
        initComponents();
        initialization();
        addJPanelIntoContent(home);
        //performEvent();
    }
    
    public NhanVienQuanKho(NhanVien nv) {
        initComponents();
        initialization();
        addJPanelIntoContent(home);
        performEvent(nv);
        displayNameStaff(nv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        hello = new javax.swing.JLabel();
        leftControl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));

        logout.setBackground(new java.awt.Color(255, 51, 0));
        logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sign_out_50px.png"))); // NOI18N
        logout.setText("Đăng xuất");
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        hello.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        hello.setForeground(new java.awt.Color(0, 153, 255));
        hello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hello.setText("Xin chào :");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addComponent(hello, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 632, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(hello, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1410, 60));

        leftControl.setBackground(new java.awt.Color(255, 255, 255));
        leftControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/paid_bill_64px.png"))); // NOI18N
        jButton1.setText("Quản Lý Hóa Đơn");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        leftControl.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, 75));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/receipt_dollar_64px.png"))); // NOI18N
        jButton3.setText("Quản Lý Phiếu Nhập");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftControl.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 75));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 51, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/account.png"))); // NOI18N
        jButton5.setText("Quản Lý Tài Khoản");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftControl.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 290, 75));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 51, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/customer.png"))); // NOI18N
        jButton6.setText("Quản Lý Khách Hàng");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftControl.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 290, 70));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(153, 51, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/staff.png"))); // NOI18N
        jButton7.setText("Quản Lý Nhân Viên");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftControl.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 290, 75));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 51, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/supplier_64px.png"))); // NOI18N
        jButton9.setText("Quản Lý Nhà Cung Cấp");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftControl.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 290, 75));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 51, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/sale_64px.png"))); // NOI18N
        jButton8.setText("Quản Lý Khuyến Mãi");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftControl.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, 90));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 51, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/book.png"))); // NOI18N
        jButton2.setText("Quản Lý Sách");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        leftControl.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 290, 70));

        homeBtn.setBackground(new java.awt.Color(255, 255, 255));
        homeBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(153, 51, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/google_home_64px.png"))); // NOI18N
        homeBtn.setText("Trang Chủ");
        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftControl.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 80));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 51, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/keyboard_64px.png"))); // NOI18N
        jButton10.setText("Quản Lý Thể Loại");
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftControl.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 290, 90));

        background.add(leftControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 740));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 1120, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienQuanKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienQuanKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienQuanKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienQuanKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienQuanKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel hello;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel leftControl;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        this.setLocationRelativeTo(null);
        setBackgroundForButtonMenu("Trang Chủ");
    }
    
    private void addJPanelIntoContent(JPanel p){
        content.removeAll();
        content.revalidate();
        content.repaint();
        p.setSize(1200, 640);
        p.setVisible(true);
        content.add(p);
    }

    private void performEvent(NhanVien nv) {
        logout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất ?", "Đăng xuất", 0) == 0){
                    dispose();
                    new Login().setVisible(true);
                }
            }
        });
        
        ActionListener ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setBackgroundForMenu();
                setBackgroundForButtonMenu(e.getActionCommand());
                switch(e.getActionCommand()){
                    case "Quản Lý Sách":{
                        
                        addJPanelIntoContent(book);
                        break;
                    }
                    case "Quản Lý Hóa Đơn":{
                        addJPanelIntoContent(new QuanLyHoaDon(nv));
                        break;
                    }
                    case "Quản Lý Phiếu Nhập":{
                        receipt = new QuanLyPhieuNhap(nv);
                        addJPanelIntoContent(receipt);
                        break;
                    }
                    case "Quản Lý Tài Khoản":{
                        addJPanelIntoContent(accountCus);
                        break;
                    }
                    case "Quản Lý Nhân Viên":{
                        addJPanelIntoContent(staff);
                        break;
                    }
                    case "Quản Lý Nhà Cung Cấp":{
                        addJPanelIntoContent(supplier);
                        break;
                    }
                    case "Quản Lý Khách Hàng":{
                        addJPanelIntoContent(customer);
                        break;
                    }
                    case "Quản Lý Khuyến Mãi":{
                        addJPanelIntoContent(sale);
                        break;
                    }
                    case "Trang Chủ":{
                        addJPanelIntoContent(home);
                        break;
                    }
                    case "Quản Lý Thể Loại":{
                        addJPanelIntoContent(theloai);
                        break;
                    }
                }
            }
        };
        Arrays.stream(leftControl.getComponents()).forEach(
               c->{
                   if(c instanceof JButton){
                       ((JButton)c).addActionListener(ac);
                       ((JButton)c).setActionCommand(((JButton)c).getActionCommand());
                   }
               }
        );
        homeBtn.addActionListener(ac);
        homeBtn.setActionCommand(homeBtn.getActionCommand());
    }

    private void displayNameStaff(NhanVien nv) {
        hello.setText("Xin chào : " + nv.getTenNhanVien());
    }
    
     public void setBackgroundForMenu(){
        Arrays.stream(leftControl.getComponents()).forEach(
               c->{
                   if(c instanceof JButton){
                       ((JButton)c).setBackground(Color.WHITE);
                   }
               }
        );
    }
     
     public void setBackgroundForButtonMenu(String name){
         Arrays.stream(leftControl.getComponents()).forEach(
               c->{
                   if(c instanceof JButton){
                       String s = ((JButton)c).getActionCommand();
                       if(s.compareTo(name) == 0){
                           //((JButton)c).setBackground(new Color(190,190,190));
                          ((JButton)c).setBackground(new Color(96,215,255));
                       }
                   }
               }
        );
     }
}
