/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QLNhaCungCap;

import DAO.NhaCungCapDao;
import BUS.NhaCungCapBus;
import DTO.NhaCungCap;
import ProcessingFunction.ConnectionDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class SuaNhaCungCap extends javax.swing.JFrame {
    NhaCungCapBus nhacungcapbus = new NhaCungCapBus();
    ArrayList<NhaCungCap> arr = nhacungcapbus.getAllData();
    ConnectionDB conn = new ConnectionDB();

    public SuaNhaCungCap() {
        initComponents();
        initialization();
        loadNCC();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manhacungcap = new javax.swing.JComboBox<>();
        trangthai = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tennhacungcap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        sodienthoai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addImage = new javax.swing.JButton();
        diachi = new javax.swing.JTextField();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manhacungcap.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manhacungcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manhacungcapActionPerformed(evt);
            }
        });

        trangthai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Trạng thái");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Mã Nhà Cung Cấp");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Tên Nhà Cung Cấp");

        tennhacungcap.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sửa Nhà Cung Cấp");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Số Điện Thoại");

        sodienthoai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Địa Chỉ");

        addImage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addImage.setText("Cập Nhật");
        addImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addImageMouseClicked(evt);
            }
        });

        diachi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        refreshBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        refreshBtn.setText("Làm lại");
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(manhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tennhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(refreshBtn)
                        .addGap(51, 51, 51)
                        .addComponent(addImage)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(manhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tennhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addImage)
                    .addComponent(refreshBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manhacungcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manhacungcapActionPerformed
        // TODO add your handling code here:
        int select = manhacungcap.getSelectedIndex();
        if (select == 0) {
            tennhacungcap.setText("");
            sodienthoai.setText("");
            diachi.setText("");
            trangthai.setText("");
            return;
        }
        NhaCungCap ncc1 = nhacungcapbus.getNCCbyID(Integer.valueOf(String.valueOf(manhacungcap.getSelectedItem())));
        System.out.println(manhacungcap.getSelectedItem());
        if (ncc1 == null) {
            JOptionPane.showMessageDialog(null, "Lỗi khi load dữ liệu");
            return;
        }
        tennhacungcap.setText(ncc1.getTenNhaCungCap());
        sodienthoai.setText(ncc1.getSDT());
        diachi.setText(ncc1.getDiaChi());
        trangthai.setText(String.valueOf(ncc1.isTrangThai()));
    }//GEN-LAST:event_manhacungcapActionPerformed

    private void addImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addImageMouseClicked
        // TODO add your handling code here:
        if (tennhacungcap.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Nhập tên nhà cung cấp!");
            tennhacungcap.requestFocus();
            return;
        }
        if (sodienthoai.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Nhập số điện thoại nhà cung cấp!");
            sodienthoai.requestFocus();
            return;
        }
        if (sodienthoai.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Số điện thoại phải là 10 số");
            sodienthoai.requestFocus();
            return;
        }
        if (diachi.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Nhập địa chỉ nhà cung cấp!");
            diachi.requestFocus();
            return;
        }

        try {
            int tmp = Integer.valueOf(sodienthoai.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Số điện thoại nhà cung cấp phải là số");
            sodienthoai.requestFocus();
            return;
        }
        if (trangthai.getText().compareTo("true") != 0 && trangthai.getText().compareTo("false") != 0) {
            JOptionPane.showMessageDialog(null, "Trạng thái phải là true hoặc false, mời bạn nhập lại!");
            trangthai.requestFocus();
            return;
        }
        NhaCungCap ncc = new NhaCungCap(Integer.valueOf(String.valueOf(manhacungcap.getSelectedItem())),
                tennhacungcap.getText(),
                sodienthoai.getText(),
                diachi.getText(),
                Boolean.valueOf(trangthai.getText()));
        boolean ok = nhacungcapbus.updateNCC(ncc);
        if (ok) {
            JOptionPane.showMessageDialog(null, "Sửa thành công");
            manhacungcap.setSelectedIndex(0);
            tennhacungcap.setText("");
            sodienthoai.setText("");
            diachi.setText("");
            trangthai.setText("");
            return;
        }
        JOptionPane.showMessageDialog(null, "Không thể thêm.Error!!!");
    }//GEN-LAST:event_addImageMouseClicked

    private void refreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseClicked
        // TODO add your handling code here:
        manhacungcap.setSelectedIndex(0);
        tennhacungcap.setText("");
        sodienthoai.setText("");
        diachi.setText("");
        trangthai.setText("");
    }//GEN-LAST:event_refreshBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaNhaCungCap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImage;
    private javax.swing.JTextField diachi;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> manhacungcap;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField sodienthoai;
    private javax.swing.JTextField tennhacungcap;
    private javax.swing.JTextField trangthai;
    // End of variables declaration//GEN-END:variables
    public void loadNCC() {
        manhacungcap.addItem("[Lựa chọn]");
        for (NhaCungCap a : arr) {
            manhacungcap.addItem(String.valueOf(a.getMaNhaCungCap()));
        }
    }

    private void initialization() {
        this.setLocationRelativeTo(null);
    }
}
